### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by YaoXinZhi** [yangkuoone/PDGNet#1]
When i run the demo code in your REDEME, iget the error like this:

[wangli@localhost code]$ python2 train.py
load cv data ...
building test data...
loading data...
('n_disease:', 12500)
('n_gene:', 8601)
('n_test_data:', 3354)
('n_symptom:', 3990)
('n_go:', 6349)
('n_dimension (dis_matrix):', 5295)
('n_dimension (gene_matrix):', 6414)
train model...
2021-07-26 16:39:23.017313: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
('====================Epoch ', 0, '====================')
build train data ...
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    t = Train()
  File "train.py", line 23, in __init__
    self.train()
  File "train.py", line 70, in train
    self.run_epoch(sess, model)
  File "train.py", line 95, in run_epoch
    self.train_dg_net(sess, model)
  File "train.py", line 123, in train_dg_net
    _, loss, y = model.train_dg_net(sess, feed_dict)
  File "/home/wangli/xzyao/JBI_work/PDGNet/PDGNet-master/code/model.py", line 122, in train_dg_net
    return sess.run([self.optimizer_dg, self.dg_loss, self.dg_y], feed_dict)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4] = 10385 is not in [0, 8601)
	 [[Node: embedding_lookup_3 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Const_3"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Const_3, _arg_Placeholder_0_0)]]

Caused by op u'embedding_lookup_3', defined at:
  File "train.py", line 159, in <module>
    t = Train()
  File "train.py", line 23, in __init__
    self.train()
  File "train.py", line 62, in train
    model = Model(self.args, data)
  File "/home/wangli/xzyao/JBI_work/PDGNet/PDGNet-master/code/model.py", line 9, in __init__
    self._add_model(args, data)
  File "/home/wangli/xzyao/JBI_work/PDGNet/PDGNet-master/code/model.py", line 42, in _add_model
    self.gene_embedding_s = tf.nn.embedding_lookup(self.gene_matrix_s,self.dis)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 328, in embedding_lookup
    transform_fn=None)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/wangli/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[4] = 10385 is not in [0, 8601)
	 [[Node: embedding_lookup_3 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Const_3"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Const_3, _arg_Placeholder_0_0)]]

So, can you help me to fix it.

**Comment by YaoXinZhi** [comment]
My Tensorflow version is 1.4.0, Numpy is 1.16.6, and Python2

**Comment by yangkuoone** [comment]
I run this code based on GPU (i.e., 1080Ti). Does your machine have a GPU, i.e., 1080Ti or above? I didn't run this code using the machine without GPU.

**Comment by night-changes** [comment]
> I run this code based on GPU (i.e., 1080Ti). Does your machine have a GPU, i.e., 1080Ti or above? I didn't run this code using the machine without GPU.

I run on a machine with GPU, and the same bug occurs
